import { ProfileQuestion } from './types';

export const PROFILE_QUESTIONS: ProfileQuestion[] = [
  {
    key: 'one_word',
    label_ja: 'あなたを一言で表現すると？',
    label_en: 'Describe yourself in one word?',
    type: 'text',
    placeholder_ja: '例: 好奇心旺盛、自由人...',
    placeholder_en: 'e.g. Curious, free-spirit...',
    layer: 1,
  },
  {
    key: 'indoor_outdoor',
    label_ja: 'インドア派？アウトドア派？',
    label_en: 'Indoor or outdoor person?',
    type: 'select',
    options: [
      { value: 'indoor', label_ja: 'インドア派', label_en: 'Indoor' },
      { value: 'outdoor', label_ja: 'アウトドア派', label_en: 'Outdoor' },
      { value: 'both', label_ja: 'どちらも', label_en: 'Both' },
    ],
    layer: 1,
  },
  {
    key: 'morning_night',
    label_ja: '朝型？夜型？',
    label_en: 'Morning person or night owl?',
    type: 'select',
    options: [
      { value: 'morning', label_ja: '朝型', label_en: 'Morning' },
      { value: 'night', label_ja: '夜型', label_en: 'Night' },
      { value: 'both', label_ja: 'どちらも', label_en: 'Both' },
    ],
    layer: 1,
  },
  {
    key: 'current_hobby',
    label_ja: '今ハマっていることは？',
    label_en: "What's your current hobby?",
    type: 'text',
    placeholder_ja: '例: 読書、ランニング、料理...',
    placeholder_en: 'e.g. Reading, running, cooking...',
    layer: 1,
  },
  {
    key: 'favorite_food',
    label_ja: '好きな食べ物は？',
    label_en: "What's your favorite food?",
    type: 'text',
    placeholder_ja: '例: ラーメン、寿司、カレー...',
    placeholder_en: 'e.g. Ramen, sushi, curry...',
    layer: 1,
  },
  {
    key: 'dream_country',
    label_ja: '行ってみたい国は？',
    label_en: 'What country do you dream of visiting?',
    type: 'text',
    placeholder_ja: '例: アイスランド、ブラジル...',
    placeholder_en: 'e.g. Iceland, Brazil...',
    layer: 1,
  },
  {
    key: 'biggest_worry',
    label_ja: '今一番気になっていることは？',
    label_en: "What's your biggest worry right now?",
    type: 'text',
    placeholder_ja: '匿名で共有されます / Shared anonymously',
    placeholder_en: 'This will be shared anonymously',
    layer: 2,
  },
  {
    key: 'future_dream',
    label_ja: '将来の夢は？',
    label_en: "What's your dream for the future?",
    type: 'text',
    placeholder_ja: '匿名で共有されます / Shared anonymously',
    placeholder_en: 'This will be shared anonymously',
    layer: 2,
  },
  {
    key: 'secret',
    label_ja: '誰にも言えない秘密は？',
    label_en: "What's a secret you haven't told anyone?",
    type: 'text',
    placeholder_ja: '匿名で共有されます / Shared anonymously',
    placeholder_en: 'This will be shared anonymously',
    layer: 2,
  },
];
