import { ProfileQuestion } from './types';

export const PROFILE_QUESTIONS: ProfileQuestion[] = [
  {
    key: 'mbti',
    label_ja: 'あなたのMBTIは？',
    label_en: "What's your MBTI?",
    type: 'select',
    options: [
      { value: 'INTJ', label_ja: 'INTJ', label_en: 'INTJ' },
      { value: 'INTP', label_ja: 'INTP', label_en: 'INTP' },
      { value: 'ENTJ', label_ja: 'ENTJ', label_en: 'ENTJ' },
      { value: 'ENTP', label_ja: 'ENTP', label_en: 'ENTP' },
      { value: 'INFJ', label_ja: 'INFJ', label_en: 'INFJ' },
      { value: 'INFP', label_ja: 'INFP', label_en: 'INFP' },
      { value: 'ENFJ', label_ja: 'ENFJ', label_en: 'ENFJ' },
      { value: 'ENFP', label_ja: 'ENFP', label_en: 'ENFP' },
      { value: 'ISTJ', label_ja: 'ISTJ', label_en: 'ISTJ' },
      { value: 'ISFJ', label_ja: 'ISFJ', label_en: 'ISFJ' },
      { value: 'ESTJ', label_ja: 'ESTJ', label_en: 'ESTJ' },
      { value: 'ESFJ', label_ja: 'ESFJ', label_en: 'ESFJ' },
      { value: 'ISTP', label_ja: 'ISTP', label_en: 'ISTP' },
      { value: 'ISFP', label_ja: 'ISFP', label_en: 'ISFP' },
      { value: 'ESTP', label_ja: 'ESTP', label_en: 'ESTP' },
      { value: 'ESFP', label_ja: 'ESFP', label_en: 'ESFP' },
    ],
    layer: 1,
  },
  {
    key: 'indoor_outdoor',
    label_ja: 'インドア派？アウトドア派？',
    label_en: 'Indoor or outdoor person?',
    type: 'select',
    options: [
      { value: 'indoor', label_ja: 'インドア派', label_en: 'Indoor' },
      { value: 'outdoor', label_ja: 'アウトドア派', label_en: 'Outdoor' },
      { value: 'both', label_ja: 'どちらも', label_en: 'Both' },
    ],
    layer: 1,
  },
  {
    key: 'morning_night',
    label_ja: '朝型？夜型？',
    label_en: 'Morning person or night owl?',
    type: 'select',
    options: [
      { value: 'morning', label_ja: '朝型', label_en: 'Morning' },
      { value: 'night', label_ja: '夜型', label_en: 'Night' },
      { value: 'both', label_ja: 'どちらも', label_en: 'Both' },
    ],
    layer: 1,
  },
  {
    key: 'current_hobby',
    label_ja: '今ハマっていることは？',
    label_en: "What's your current hobby?",
    type: 'text',
    placeholder_ja: '例: 読書、ランニング、料理...',
    placeholder_en: 'e.g. Reading, running, cooking...',
    layer: 1,
  },
  {
    key: 'favorite_food',
    label_ja: '好きな食べ物は？',
    label_en: "What's your favorite food?",
    type: 'text',
    placeholder_ja: '例: ラーメン、寿司、カレー...',
    placeholder_en: 'e.g. Ramen, sushi, curry...',
    layer: 1,
  },
  {
    key: 'dream_country',
    label_ja: '行ってみたい国は？',
    label_en: 'What country do you dream of visiting?',
    type: 'text',
    placeholder_ja: '例: アイスランド、ブラジル...',
    placeholder_en: 'e.g. Iceland, Brazil...',
    layer: 1,
  },
  {
    key: 'biggest_worry',
    label_ja: '今一番気になっていることは？',
    label_en: "What's your biggest worry right now?",
    type: 'text',
    placeholder_ja: '匿名で共有されます / Shared anonymously',
    placeholder_en: 'This will be shared anonymously',
    layer: 2,
  },
  {
    key: 'future_dream',
    label_ja: '将来の夢は？',
    label_en: "What's your dream for the future?",
    type: 'text',
    placeholder_ja: '匿名で共有されます / Shared anonymously',
    placeholder_en: 'This will be shared anonymously',
    layer: 2,
  },
  {
    key: 'secret',
    label_ja: '誰にも言えない秘密は？',
    label_en: "What's a secret you haven't told anyone?",
    type: 'text',
    placeholder_ja: '匿名で共有されます / Shared anonymously',
    placeholder_en: 'This will be shared anonymously',
    layer: 2,
  },
];
